### ISSUE TITLE
Exception on exit

### ISSUE THREAD

**Issue by JulioPM** [fanzhe98/modbuspp#1]
Hello,

i just started using your library but I found an issue.

When I instantiate the class, the code works but I get an exception when the program exits. See below and attached screenshot.

Output : 
```
address : 192.168.1.21 port : 502
reg #1 : 1 reg #2 : 2
Found Proper Host 192.168.1.21 and Port 502
Socket Opened Successfully
Connected
Register #0 holds : 0x7fff360f17ae
Socket Closed
*** Error in `./modbus_retriever': munmap_chunk(): invalid pointer: 0x00007fff360f1800 ***
Abandon (core dumped)
```

@fanzhe98 Thanks you for helping

**Comment by zkasa** [comment]
It is because of 

`/**
 * Destructor of Modbus Object
 */
modbus::~modbus(void) {
    //delete(&HOST);
    //delete(&PORT);
    //delete(&_socket);
    //delete(&_server);
}
`
Many places in the code with dynamic deletion of the statically allocated data! Very bad C++ code!

**Comment by JulioPM** [comment]
Yes I saw it afterwards, I ended up deleting those lines.

Plus at some other places in the code, he did the same aswell- deleted those too.
