### ISSUE TITLE
modbus_write_coils not working

### ISSUE THREAD

**Issue by BlackHoneyBear** [fanzhe98/modbuspp#6]
void modbus::modbus_write(int address, int amount, int func, uint16_t *value) {
	if (func == WRITE_COIL || func == WRITE_REG) {
		uint8_t to_send[12];
		modbus_build_request(to_send, address, func);
		to_send[5] = 6;
		to_send[10] = (uint8_t)(value[0] >> 8);
		to_send[11] = (uint8_t)(value[0] & 0x00FF);
		modbus_send(to_send, 12);
	}
	else if (func == WRITE_REGS) {
		uint8_t* to_send = new uint8_t[13 + 2 * amount];
		modbus_build_request(to_send, address, func);
		to_send[5] = (uint8_t)(5 + 2 * amount);
		to_send[10] = (uint8_t)(amount >> 8);
		to_send[11] = (uint8_t)(amount & 0x00FF);
		to_send[12] = (uint8_t)(2 * amount);
		for (int i = 0; i < amount; i++) {
			to_send[13 + 2 * i] = (uint8_t)(value[i] >> 8);
			to_send[14 + 2 * i] = (uint8_t)(value[i] & 0x00FF);
		}
		cout << to_send << endl;
		modbus_send(to_send, 13 + 2 * amount);
	}
	else if (func == WRITE_COILS) {

		uint8_t* to_send = new uint8_t[14 + (amount - 1) / 8];
		modbus_build_request(to_send, address, func);
		to_send[5] = (uint8_t)(7 + (amount - 1) / 8);
		to_send[10] = (uint8_t)(amount >> 8);
		to_send[11] = (uint8_t)(amount>>8);
		to_send[12] = (uint8_t)((amount + 7) / 8);
		for (int i = 0; i < amount; i++) {
			to_send[13 + (i - 1) / 8] += (uint8_t)(value[i] << (i % 8));
		}
		cout << to_send << endl;
		modbus_send(to_send, 14 + (amount - 1) / 8);
	}
}

**Comment by facundo2912** [comment]
solve it by replacing 7 with 9 (7 + (quantity -1) / 8) on line # 146

**Comment by konsolenritter** [comment]
Please proof if my last commit to https://github.com/konsolenritter/modbuspp/commit/3318c0b66b9b827f73482217b2444fb82dea6e42 does work for you. (A lot of fixing even regarding the WRITE_COILS. It failed in a many ways before, e.g. limited to four coils etc.)

**Comment by fz-lyu** [comment]
@konsolenritter 's fix should be correct, I referenced his solution and update my code
