### ISSUE TITLE
illegal data values 

### ISSUE THREAD

**Issue by BlackHoneyBear** [fanzhe98/modbuspp#7]
when "modbus_write_coil"s function calls it gives me "illegal data values" error. i do to_send[11] = (uint8_t)(amount); in func == WRITE_COILS of "modbus_write" function butt it did not write multiple coils coils

**Comment by konsolenritter** [comment]
That should be fixed by my last commit to https://github.com/konsolenritter/modbuspp/commit/3318c0b66b9b827f73482217b2444fb82dea6e42 Proof if that works for you.

**Comment by fz-lyu** [comment]
@konsolenritter 's fix should be correct, I referenced his solution and update my code
