### ISSUE TITLE
modbus_write fails to set correct size in case of WRITE_REGS (mb fn 0x10)

### ISSUE THREAD

**Issue by konsolenritter** [fanzhe98/modbuspp#8]
The length coding field in the MBAP header part of the mb/tcp ADU is wrong calculated, so enforcing mb receivers to read too few holding registers from the request.

I'm in C and C++ and Labview and Git, but i'm totally newb to the github thing. I hope to provide a new version or pull request the right way...

**Comment by why-you-trust-me** [comment]
How to solve this problem， 0x10 function can't work.

**Comment by konsolenritter** [comment]
Sorry, i'm to shy or too stupid to get a commit or pull request inserted into this github thing. :-(

To be short you have to (at least, there are other pitfalls) patch line #134 in the modbus.cpp where something like "(5 + 2 * amount)" resembles. You should change it to "(7 + 2 * amount)" to correct for the right value going to the length coding field. So the receivers will read the (otherwise missed) last register (word=2 byte).

I hope that this will be clear enough, sorry for my bad english skills. There are other pitfalls regarding timeouts, exceptions and so on. I develop them further sometimes. Don't know why fanzhe doesn't open that project for others to participate or if it would be correct (in the terms of the license) to do just a spinoff in my own github account. Sorry,  i'm totally newb to github.  A little bit frustrating for a developer who is used to have the full control over  a projects code...

**Comment by konsolenritter** [comment]
> How to solve this problem， 0x10 function can't work.

What exactly is your question? What do you mean with "can't work"? Do you meant "don't work in the moment" instead?

**Comment by facundo2912** [comment]
with the above said when replacing the 5 with the 7 can already be written in multiple registers, but the illegal data problem continues when writing in multiple coils

**Comment by konsolenritter** [comment]
Regarding the "writing multiple coils" fc (0x0F) they could be fixed by commit https://github.com/konsolenritter/modbuspp/commit/3318c0b66b9b827f73482217b2444fb82dea6e42 as of my fork.

**Comment by fz-lyu** [comment]
@konsolenritter 's fix should be correct, I referenced his solution and update my code

**Comment by fz-lyu** [comment]
@konsolenritter Thank you for your solution. For opening the projects you mentioned, the way github works is that you make a fork, and create a pull request to my repo. Directly pushing code to other people's repo is usually a dangerous behavior.

Thank you again for the fix.
