### ISSUE TITLE
shit code 

### ISSUE THREAD

**Issue by WuYanZhong** [fanzhe98/modbuspp#9]
if server disconnect, client recv always wait message?

**Comment by konsolenritter** [comment]
Maybe something of what you wrote above is fixed by commit https://github.com/konsolenritter/modbuspp/commit/cfa7f0e5474bbc7e7875a894124df201d378363c as of my fork of the repo.

**Comment by WuYanZhong** [comment]
Yes, but there are still many problems~

**Comment by fanzhe98** [comment]
@WuYanZhong Behave yourself.

**Comment by fanzhe98** [comment]
@WuYanZhong I also suggest you learn how to communicate.
